language: objective-c
cache: cocoapods
notifications:
  email: false
post_install:
  - bundle exec pod install
script:
  - xcodebuild test -workspace PrimeFactors.xcworkspace -scheme PrimeFactors -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
