language: objc
rvm:
  - 2.0.0
cache: cocoapods
podfile: Podfile
notifications:
  email: false
before_install:
  - gem install bundler
  - bundle
  - bundle exec pod install
script:
  - set -o pipefail && xcodebuild test -workspace PrimeFactors.xcworkspace -scheme PrimeFactors -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
