language: objective-c
cache: cocoapods
podfile: Podfile
notifications:
  email: false
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document
  - pod install
script:
  - xcodebuild test -workspace PrimeFactors.xcworkspace -scheme PrimeFactors -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
